import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";


const Main = () => {
  const router = useRouter();

  useEffect(() => {
    router.push("/home");
  });

  return (
    <>
      <Head>
        <title>Ybiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Redirecting...
      </main>    
    </>
  );
}

export default Main;